const data = [{
    id: 3,
    name: "Cancha de Fútbol 11 Estadio",
    venue: "Polideportivo Municipal",
    club: "polideportivo",
    sport: "futbol",
    price: 60,
    rating: 4.3,
    reviews: 156,
    address: "Av. Universitaria 789, Santiago de Surco",
    phone: "+51 1 456-7890",
    coordinates: { lat: -12.1391, lng: -76.9938 },
    images: [
      "/placeholder.svg?height=400&width=600&text=Estadio+Futbol+11",
      "/placeholder.svg?height=400&width=600&text=Estadio+Futbol+11+Vista+2",
      "/placeholder.svg?height=400&width=600&text=Estadio+Futbol+11+Vista+3",
    ],
    description: "Cancha reglamentaria de fútbol 11 con césped natural. Ideal para partidos oficiales y torneos.",
    amenities: ["Césped Natural", "Vestuarios", "Tribuna", "Iluminación", "Cafetería"],
    availability: ["06:00", "07:00", "08:00", "15:00", "16:00", "17:00", "18:00"],
    surface: "Césped Natural",
    capacity: "22 jugadores",
  },
  {
    id: 4,
    name: "Cancha de Tenis Arcilla #1",
    venue: "Club Deportivo Central",
    club: "club-central",
    sport: "tenis",
    price: 40,
    rating: 4.8,
    reviews: 203,
    address: "Jr. Lampa 321, Cercado de Lima",
    phone: "+51 1 567-8901",
    coordinates: { lat: -12.0464, lng: -77.0428 },
    images: [
      "/placeholder.svg?height=400&width=600&text=Tenis+Arcilla",
      "/placeholder.svg?height=400&width=600&text=Tenis+Arcilla+Vista+2",
    ],
    description: "Cancha de tenis con superficie de arcilla. Mantenimiento diario y excelente iluminación nocturna.",
    amenities: ["Superficie Arcilla", "Iluminación", "Vestuarios", "Tienda Pro Shop"],
    availability: ["08:00", "09:00", "10:00", "11:00", "15:00", "16:00", "17:00", "18:00"],
    surface: "Arcilla",
    capacity: "2-4 jugadores",
  },
  {
    id: 5,
    name: "Cancha de Tenis Dura #2",
    venue: "Club Deportivo Este",
    club: "club-este",
    sport: "tenis",
    price: 38,
    rating: 4.6,
    reviews: 94,
    address: "Av. La Molina 654, La Molina",
    phone: "+51 1 678-9012",
    coordinates: { lat: -12.0792, lng: -76.9447 },
    images: [
      "/placeholder.svg?height=400&width=600&text=Tenis+Dura",
      "/placeholder.svg?height=400&width=600&text=Tenis+Dura+Vista+2",
    ],
    description: "Cancha de tenis con superficie dura. Ideal para juego rápido y competitivo.",
    amenities: ["Superficie Dura", "Iluminación", "Vestuarios", "Estacionamiento"],
    availability: ["07:00", "08:00", "09:00", "16:00", "17:00", "18:00", "19:00"],
    surface: "Superficie Dura",
    capacity: "2-4 jugadores",
  },
  {
    id: 6,
    name: "Cancha de Pádel Cristal #1",
    venue: "Club Deportivo Este",
    club: "club-este",
    sport: "padel",
    price: 25,
    rating: 4.2,
    reviews: 67,
    address: "Av. La Molina 654, La Molina",
    phone: "+51 1 678-9012",
    coordinates: { lat: -12.0792, lng: -76.9447 },
    images: [
      "/placeholder.svg?height=400&width=600&text=Padel+Cristal",
      "/placeholder.svg?height=400&width=600&text=Padel+Cristal+Vista+2",
    ],
    description: "Cancha de pádel con paredes de cristal y césped artificial de alta calidad.",
    amenities: ["Paredes Cristal", "Césped Artificial", "Iluminación", "Vestuarios"],
    availability: ["08:00", "09:00", "10:00", "15:00", "16:00", "17:00", "18:00", "19:00"],
    surface: "Césped Artificial",
    capacity: "4 jugadores",
  },
  {
    id: 7,
    name: "Cancha de Pádel Panorámica #2",
    venue: "Club Deportivo Norte",
    club: "club-norte",
    sport: "padel",
    price: 28,
    rating: 4.4,
    reviews: 82,
    address: "Av. Javier Prado Este 123, San Isidro",
    phone: "+51 1 234-5678",
    coordinates: { lat: -12.0969, lng: -77.0378 },
    images: [
      "/placeholder.svg?height=400&width=600&text=Padel+Panoramica",
      "/placeholder.svg?height=400&width=600&text=Padel+Panoramica+Vista+2",
    ],
    description: "Cancha de pádel panorámica con las mejores vistas de la ciudad. Superficie profesional.",
    amenities: ["Vista Panorámica", "Superficie Profesional", "Iluminación", "Vestuarios"],
    availability: ["07:00", "08:00", "09:00", "15:00", "16:00", "17:00", "18:00"],
    surface: "Césped Artificial",
    capacity: "4 jugadores",
  },
  {
    id: 8,
    name: "Cancha de Básquet Indoor",
    venue: "Polideportivo Municipal",
    club: "polideportivo",
    sport: "basquet",
    price: 30,
    rating: 4.0,
    reviews: 45,
    address: "Av. Universitaria 789, Santiago de Surco",
    phone: "+51 1 456-7890",
    coordinates: { lat: -12.1391, lng: -76.9938 },
    images: [
      "/placeholder.svg?height=400&width=600&text=Basquet+Indoor",
      "/placeholder.svg?height=400&width=600&text=Basquet+Indoor+Vista+2",
    ],
    description: "Cancha de básquet con superficie de madera y tableros oficiales. Perfecta para partidos 3x3 o 5x5.",
    amenities: ["Superficie Madera", "Tableros Oficiales", "Aire Acondicionado", "Vestuarios"],
    availability: ["09:00", "10:00", "11:00", "15:00", "16:00", "17:00", "18:00", "19:00"],
    surface: "Madera",
    capacity: "10 jugadores",
  },
  {
    id: 9,
    name: "Cancha de Vóley Playa",
    venue: "Club Deportivo Oeste",
    club: "club-oeste",
    sport: "voley",
    price: 20,
    rating: 3.9,
    reviews: 38,
    address: "Malecón de la Costa Verde, Chorrillos",
    phone: "+51 1 789-0123",
    coordinates: { lat: -12.1404, lng: -77.0219 },
    images: [
      "/placeholder.svg?height=400&width=600&text=Voley+Playa",
      "/placeholder.svg?height=400&width=600&text=Voley+Playa+Vista+2",
    ],
    description: "Cancha de vóley con arena fina importada. Ideal para entrenamientos y torneos de playa.",
    amenities: ["Arena Importada", "Red Profesional", "Duchas", "Bar de Playa"],
    availability: ["08:00", "09:00", "10:00", "11:00", "15:00", "16:00", "17:00"],
    surface: "Arena",
    capacity: "6 jugadores",
  },
  {
    id: 10,
    name: "Cancha de Fútbol 5 Nocturna",
    venue: "Club Deportivo Central",
    club: "club-central",
    sport: "futbol",
    price: 42,
    rating: 4.6,
    reviews: 156,
    address: "Jr. Lampa 321, Cercado de Lima",
    phone: "+51 1 567-8901",
    coordinates: { lat: -12.0464, lng: -77.0428 },
    images: [
      "/placeholder.svg?height=400&width=600&text=Futbol+5+Nocturna",
      "/placeholder.svg?height=400&width=600&text=Futbol+5+Nocturna+Vista+2",
    ],
    description: "Cancha de fútbol 5 con iluminación LED profesional. Perfecta para partidos nocturnos.",
    amenities: ["Iluminación LED", "Césped Sintético", "Vestuarios", "Seguridad 24h"],
    availability: ["18:00", "19:00", "20:00", "21:00", "22:00"],
    surface: "Césped Sintético",
    capacity: "10 jugadores",
  },
  {
    id: 11,
    name: "Cancha de Tenis Grass",
    venue: "Club Deportivo Sur",
    club: "club-sur",
    sport: "tenis",
    price: 50,
    rating: 4.9,
    reviews: 78,
    address: "Calle Los Pinos 456, Miraflores",
    phone: "+51 1 345-6789",
    coordinates: { lat: -12.1191, lng: -77.0282 },
    images: [
      "/placeholder.svg?height=400&width=600&text=Tenis+Grass",
      "/placeholder.svg?height=400&width=600&text=Tenis+Grass+Vista+2",
    ],
    description: "Cancha de tenis con césped natural tipo Wimbledon. La más exclusiva de Lima.",
    amenities: ["Césped Natural", "Vestuarios VIP", "Servicio de Toallas", "Club House"],
    availability: ["08:00", "09:00", "10:00", "15:00", "16:00", "17:00"],
    surface: "Césped Natural",
    capacity: "2-4 jugadores",
  },
  {
    id: 12,
    name: "Cancha de Básquet 3x3",
    venue: "Club Deportivo Norte",
    club: "club-norte",
    sport: "basquet",
    price: 25,
    rating: 4.1,
    reviews: 92,
    address: "Av. Javier Prado Este 123, San Isidro",
    phone: "+51 1 234-5678",
    coordinates: { lat: -12.0969, lng: -77.0378 },
    images: [
      "/placeholder.svg?height=400&width=600&text=Basquet+3x3",
      "/placeholder.svg?height=400&width=600&text=Basquet+3x3+Vista+2",
    ],
    description: "Cancha especializada para básquet 3x3. Superficie antideslizante y tablero profesional.",
    amenities: ["Superficie Antideslizante", "Tablero Profesional", "Iluminación", "Vestuarios"],
    availability: ["08:00", "09:00", "10:00", "14:00", "15:00", "16:00", "17:00", "18:00"],
    surface: "Sintético",
    capacity: "6 jugadores",
  }]

  const clubs = [
    { value: "club-norte", label: "Club Deportivo Norte" },
    { value: "club-sur", label: "Club Deportivo Sur" },
    { value: "polideportivo", label: "Polideportivo Municipal" },
    { value: "club-central", label: "Club Deportivo Central" },
    { value: "club-este", label: "Club Deportivo Este" },
    { value: "club-oeste", label: "Club Deportivo Oeste" },
  ]